/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedRelatoriosRouteImport } from './routes/_authed/relatorios'
import { Route as AuthedPerfilRouteImport } from './routes/_authed/perfil'
import { Route as AuthedNotificacoesRouteImport } from './routes/_authed/notificacoes'
import { Route as AuthedMeuTrabalhoRouteImport } from './routes/_authed/meu-trabalho'
import { Route as AuthedAlocacaoRouteImport } from './routes/_authed/alocacao'
import { Route as AuthedCursosIndexRouteImport } from './routes/_authed/cursos/index'
import { Route as AuthedOasOaIdRouteImport } from './routes/_authed/oas/$oaId'
import { Route as AuthedCursosImportarRouteImport } from './routes/_authed/cursos/importar'
import { Route as AuthedCursosCursoIdRouteImport } from './routes/_authed/cursos/$cursoId'
import { Route as AuthedAdminUsuariosRouteImport } from './routes/_authed/admin/usuarios'
import { Route as AuthedAdminPipelineRouteImport } from './routes/_authed/admin/pipeline'
import { Route as AuthedCursosCursoIdSetupProducaoRouteImport } from './routes/_authed/cursos/$cursoId_/setup-producao'
import { Route as AuthedCursosCursoIdOasRouteImport } from './routes/_authed/cursos/$cursoId_/oas'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRelatoriosRoute = AuthedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPerfilRoute = AuthedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificacoesRoute = AuthedNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeuTrabalhoRoute = AuthedMeuTrabalhoRouteImport.update({
  id: '/meu-trabalho',
  path: '/meu-trabalho',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAlocacaoRoute = AuthedAlocacaoRouteImport.update({
  id: '/alocacao',
  path: '/alocacao',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCursosIndexRoute = AuthedCursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOasOaIdRoute = AuthedOasOaIdRouteImport.update({
  id: '/oas/$oaId',
  path: '/oas/$oaId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCursosImportarRoute = AuthedCursosImportarRouteImport.update({
  id: '/cursos/importar',
  path: '/cursos/importar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCursosCursoIdRoute = AuthedCursosCursoIdRouteImport.update({
  id: '/cursos/$cursoId',
  path: '/cursos/$cursoId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminUsuariosRoute = AuthedAdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminPipelineRoute = AuthedAdminPipelineRouteImport.update({
  id: '/admin/pipeline',
  path: '/admin/pipeline',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCursosCursoIdSetupProducaoRoute =
  AuthedCursosCursoIdSetupProducaoRouteImport.update({
    id: '/cursos/$cursoId_/setup-producao',
    path: '/cursos/$cursoId/setup-producao',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCursosCursoIdOasRoute = AuthedCursosCursoIdOasRouteImport.update({
  id: '/cursos/$cursoId_/oas',
  path: '/cursos/$cursoId/oas',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/alocacao': typeof AuthedAlocacaoRoute
  '/meu-trabalho': typeof AuthedMeuTrabalhoRoute
  '/notificacoes': typeof AuthedNotificacoesRoute
  '/perfil': typeof AuthedPerfilRoute
  '/relatorios': typeof AuthedRelatoriosRoute
  '/admin/pipeline': typeof AuthedAdminPipelineRoute
  '/admin/usuarios': typeof AuthedAdminUsuariosRoute
  '/cursos/$cursoId': typeof AuthedCursosCursoIdRoute
  '/cursos/importar': typeof AuthedCursosImportarRoute
  '/oas/$oaId': typeof AuthedOasOaIdRoute
  '/cursos/': typeof AuthedCursosIndexRoute
  '/cursos/$cursoId/oas': typeof AuthedCursosCursoIdOasRoute
  '/cursos/$cursoId/setup-producao': typeof AuthedCursosCursoIdSetupProducaoRoute
}
export interface FileRoutesByTo {
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/alocacao': typeof AuthedAlocacaoRoute
  '/meu-trabalho': typeof AuthedMeuTrabalhoRoute
  '/notificacoes': typeof AuthedNotificacoesRoute
  '/perfil': typeof AuthedPerfilRoute
  '/relatorios': typeof AuthedRelatoriosRoute
  '/': typeof AuthedIndexRoute
  '/admin/pipeline': typeof AuthedAdminPipelineRoute
  '/admin/usuarios': typeof AuthedAdminUsuariosRoute
  '/cursos/$cursoId': typeof AuthedCursosCursoIdRoute
  '/cursos/importar': typeof AuthedCursosImportarRoute
  '/oas/$oaId': typeof AuthedOasOaIdRoute
  '/cursos': typeof AuthedCursosIndexRoute
  '/cursos/$cursoId/oas': typeof AuthedCursosCursoIdOasRoute
  '/cursos/$cursoId/setup-producao': typeof AuthedCursosCursoIdSetupProducaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/_authed/alocacao': typeof AuthedAlocacaoRoute
  '/_authed/meu-trabalho': typeof AuthedMeuTrabalhoRoute
  '/_authed/notificacoes': typeof AuthedNotificacoesRoute
  '/_authed/perfil': typeof AuthedPerfilRoute
  '/_authed/relatorios': typeof AuthedRelatoriosRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/admin/pipeline': typeof AuthedAdminPipelineRoute
  '/_authed/admin/usuarios': typeof AuthedAdminUsuariosRoute
  '/_authed/cursos/$cursoId': typeof AuthedCursosCursoIdRoute
  '/_authed/cursos/importar': typeof AuthedCursosImportarRoute
  '/_authed/oas/$oaId': typeof AuthedOasOaIdRoute
  '/_authed/cursos/': typeof AuthedCursosIndexRoute
  '/_authed/cursos/$cursoId_/oas': typeof AuthedCursosCursoIdOasRoute
  '/_authed/cursos/$cursoId_/setup-producao': typeof AuthedCursosCursoIdSetupProducaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/sso-callback'
    | '/alocacao'
    | '/meu-trabalho'
    | '/notificacoes'
    | '/perfil'
    | '/relatorios'
    | '/admin/pipeline'
    | '/admin/usuarios'
    | '/cursos/$cursoId'
    | '/cursos/importar'
    | '/oas/$oaId'
    | '/cursos/'
    | '/cursos/$cursoId/oas'
    | '/cursos/$cursoId/setup-producao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/sso-callback'
    | '/alocacao'
    | '/meu-trabalho'
    | '/notificacoes'
    | '/perfil'
    | '/relatorios'
    | '/'
    | '/admin/pipeline'
    | '/admin/usuarios'
    | '/cursos/$cursoId'
    | '/cursos/importar'
    | '/oas/$oaId'
    | '/cursos'
    | '/cursos/$cursoId/oas'
    | '/cursos/$cursoId/setup-producao'
  id:
    | '__root__'
    | '/_authed'
    | '/esqueci-senha'
    | '/login'
    | '/redefinir-senha'
    | '/sso-callback'
    | '/_authed/alocacao'
    | '/_authed/meu-trabalho'
    | '/_authed/notificacoes'
    | '/_authed/perfil'
    | '/_authed/relatorios'
    | '/_authed/'
    | '/_authed/admin/pipeline'
    | '/_authed/admin/usuarios'
    | '/_authed/cursos/$cursoId'
    | '/_authed/cursos/importar'
    | '/_authed/oas/$oaId'
    | '/_authed/cursos/'
    | '/_authed/cursos/$cursoId_/oas'
    | '/_authed/cursos/$cursoId_/setup-producao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/relatorios': {
      id: '/_authed/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthedRelatoriosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/perfil': {
      id: '/_authed/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthedPerfilRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notificacoes': {
      id: '/_authed/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthedNotificacoesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/meu-trabalho': {
      id: '/_authed/meu-trabalho'
      path: '/meu-trabalho'
      fullPath: '/meu-trabalho'
      preLoaderRoute: typeof AuthedMeuTrabalhoRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/alocacao': {
      id: '/_authed/alocacao'
      path: '/alocacao'
      fullPath: '/alocacao'
      preLoaderRoute: typeof AuthedAlocacaoRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cursos/': {
      id: '/_authed/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof AuthedCursosIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/oas/$oaId': {
      id: '/_authed/oas/$oaId'
      path: '/oas/$oaId'
      fullPath: '/oas/$oaId'
      preLoaderRoute: typeof AuthedOasOaIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cursos/importar': {
      id: '/_authed/cursos/importar'
      path: '/cursos/importar'
      fullPath: '/cursos/importar'
      preLoaderRoute: typeof AuthedCursosImportarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cursos/$cursoId': {
      id: '/_authed/cursos/$cursoId'
      path: '/cursos/$cursoId'
      fullPath: '/cursos/$cursoId'
      preLoaderRoute: typeof AuthedCursosCursoIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/usuarios': {
      id: '/_authed/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthedAdminUsuariosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/pipeline': {
      id: '/_authed/admin/pipeline'
      path: '/admin/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AuthedAdminPipelineRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cursos/$cursoId_/setup-producao': {
      id: '/_authed/cursos/$cursoId_/setup-producao'
      path: '/cursos/$cursoId/setup-producao'
      fullPath: '/cursos/$cursoId/setup-producao'
      preLoaderRoute: typeof AuthedCursosCursoIdSetupProducaoRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cursos/$cursoId_/oas': {
      id: '/_authed/cursos/$cursoId_/oas'
      path: '/cursos/$cursoId/oas'
      fullPath: '/cursos/$cursoId/oas'
      preLoaderRoute: typeof AuthedCursosCursoIdOasRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAlocacaoRoute: typeof AuthedAlocacaoRoute
  AuthedMeuTrabalhoRoute: typeof AuthedMeuTrabalhoRoute
  AuthedNotificacoesRoute: typeof AuthedNotificacoesRoute
  AuthedPerfilRoute: typeof AuthedPerfilRoute
  AuthedRelatoriosRoute: typeof AuthedRelatoriosRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAdminPipelineRoute: typeof AuthedAdminPipelineRoute
  AuthedAdminUsuariosRoute: typeof AuthedAdminUsuariosRoute
  AuthedCursosCursoIdRoute: typeof AuthedCursosCursoIdRoute
  AuthedCursosImportarRoute: typeof AuthedCursosImportarRoute
  AuthedOasOaIdRoute: typeof AuthedOasOaIdRoute
  AuthedCursosIndexRoute: typeof AuthedCursosIndexRoute
  AuthedCursosCursoIdOasRoute: typeof AuthedCursosCursoIdOasRoute
  AuthedCursosCursoIdSetupProducaoRoute: typeof AuthedCursosCursoIdSetupProducaoRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAlocacaoRoute: AuthedAlocacaoRoute,
  AuthedMeuTrabalhoRoute: AuthedMeuTrabalhoRoute,
  AuthedNotificacoesRoute: AuthedNotificacoesRoute,
  AuthedPerfilRoute: AuthedPerfilRoute,
  AuthedRelatoriosRoute: AuthedRelatoriosRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAdminPipelineRoute: AuthedAdminPipelineRoute,
  AuthedAdminUsuariosRoute: AuthedAdminUsuariosRoute,
  AuthedCursosCursoIdRoute: AuthedCursosCursoIdRoute,
  AuthedCursosImportarRoute: AuthedCursosImportarRoute,
  AuthedOasOaIdRoute: AuthedOasOaIdRoute,
  AuthedCursosIndexRoute: AuthedCursosIndexRoute,
  AuthedCursosCursoIdOasRoute: AuthedCursosCursoIdOasRoute,
  AuthedCursosCursoIdSetupProducaoRoute: AuthedCursosCursoIdSetupProducaoRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SsoCallbackRoute: SsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
